version: '3.5'
services:
  jenkins:
    build: .
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins:/var/jenkins_home
    labels:
      traefik.enable: true
      traefik.port: 8080
      traefik.frontend.rule: "Host:${DOMAIN}"
    restart: unless-stopped
volumes:
  jenkins:
networks:
  traefik:
    name: ${TRAEFIK_NETWORK}
    external: true
